[2022-03-30 20:58:59,326] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.transform_twitter_aluraonline 2022-03-26T09:00:00+00:00 [queued]>
[2022-03-30 20:58:59,343] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.transform_twitter_aluraonline 2022-03-26T09:00:00+00:00 [queued]>
[2022-03-30 20:58:59,344] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2022-03-30 20:58:59,344] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2022-03-30 20:58:59,344] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2022-03-30 20:58:59,355] {taskinstance.py:901} INFO - Executing <Task(SparkSubmitOperator): transform_twitter_aluraonline> on 2022-03-26T09:00:00+00:00
[2022-03-30 20:58:59,358] {standard_task_runner.py:54} INFO - Started process 85603 to run task
[2022-03-30 20:58:59,473] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'transform_twitter_aluraonline', '2022-03-26T09:00:00+00:00', '--job_id', '8', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/var/folders/wt/20pgcb1j11323p97x03bt_g00000gr/T/tmp8hvcjw4u']
[2022-03-30 20:58:59,483] {standard_task_runner.py:78} INFO - Job 8: Subtask transform_twitter_aluraonline
[2022-03-30 20:58:59,585] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.transform_twitter_aluraonline 2022-03-26T09:00:00+00:00 [running]> on host rafa-mac.local
[2022-03-30 20:58:59,856] {base_hook.py:89} INFO - Using connection to: id: spark_default. Host: local, Port: None, Schema: None, Login: None, Password: None, extra: XXXXXXXX
[2022-03-30 20:58:59,861] {spark_submit_hook.py:325} INFO - Spark-Submit cmd: /Users/rafa/Documents/python/spark/bin/spark-submit --master local --name twitter_transformation /Users/rafa/Documents/python/datapipeline/spark/transformation.py --src /Users/rafa/Documents/python/datapipeline/datalake/bronze/twitter_aluraonline/extract_date=2022-03-26 --dest /Users/rafa/Documents/python/datapipeline/datalake/silver/twitter_aluraonline/ --process-date 2022-03-26
[2022-03-30 20:59:07,109] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-03-30 20:59:11,105] {spark_submit_hook.py:479} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2022-03-30 20:59:11,145] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO SparkContext: Running Spark version 3.1.3
[2022-03-30 20:59:11,290] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO ResourceUtils: ==============================================================
[2022-03-30 20:59:11,291] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO ResourceUtils: No custom resources configured for spark.driver.
[2022-03-30 20:59:11,292] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO ResourceUtils: ==============================================================
[2022-03-30 20:59:11,293] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO SparkContext: Submitted application: twitter_transformation
[2022-03-30 20:59:11,407] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2022-03-30 20:59:11,427] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO ResourceProfile: Limiting resource is cpu
[2022-03-30 20:59:11,430] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2022-03-30 20:59:11,625] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO SecurityManager: Changing view acls to: rafa
[2022-03-30 20:59:11,626] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO SecurityManager: Changing modify acls to: rafa
[2022-03-30 20:59:11,626] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO SecurityManager: Changing view acls groups to:
[2022-03-30 20:59:11,628] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO SecurityManager: Changing modify acls groups to:
[2022-03-30 20:59:11,629] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:11 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(rafa); groups with view permissions: Set(); users  with modify permissions: Set(rafa); groups with modify permissions: Set()
[2022-03-30 20:59:13,505] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:13 INFO Utils: Successfully started service 'sparkDriver' on port 53521.
[2022-03-30 20:59:13,708] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:13 INFO SparkEnv: Registering MapOutputTracker
[2022-03-30 20:59:13,837] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:13 INFO SparkEnv: Registering BlockManagerMaster
[2022-03-30 20:59:14,140] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:14 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2022-03-30 20:59:14,141] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:14 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2022-03-30 20:59:14,148] {spark_submit_hook.py:479} INFO - Traceback (most recent call last):
[2022-03-30 20:59:14,149] {spark_submit_hook.py:479} INFO - File "/Users/rafa/Documents/python/datapipeline/spark/transformation.py", line 57, in <module>
[2022-03-30 20:59:14,150] {spark_submit_hook.py:479} INFO - spark = SparkSession\
[2022-03-30 20:59:14,151] {spark_submit_hook.py:479} INFO - File "/Users/rafa/Documents/python/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2022-03-30 20:59:14,152] {spark_submit_hook.py:479} INFO - File "/Users/rafa/Documents/python/spark/python/lib/pyspark.zip/pyspark/context.py", line 384, in getOrCreate
[2022-03-30 20:59:14,153] {spark_submit_hook.py:479} INFO - File "/Users/rafa/Documents/python/spark/python/lib/pyspark.zip/pyspark/context.py", line 146, in __init__
[2022-03-30 20:59:14,153] {spark_submit_hook.py:479} INFO - File "/Users/rafa/Documents/python/spark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2022-03-30 20:59:14,154] {spark_submit_hook.py:479} INFO - File "/Users/rafa/Documents/python/spark/python/lib/pyspark.zip/pyspark/context.py", line 321, in _initialize_context
[2022-03-30 20:59:14,155] {spark_submit_hook.py:479} INFO - File "/Users/rafa/Documents/python/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1568, in __call__
[2022-03-30 20:59:14,155] {spark_submit_hook.py:479} INFO - File "/Users/rafa/Documents/python/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
[2022-03-30 20:59:14,156] {spark_submit_hook.py:479} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2022-03-30 20:59:14,156] {spark_submit_hook.py:479} INFO - : java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x4ccc0db7) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x4ccc0db7
[2022-03-30 20:59:14,157] {spark_submit_hook.py:479} INFO - at org.apache.spark.storage.StorageUtils$.<init>(StorageUtils.scala:213)
[2022-03-30 20:59:14,158] {spark_submit_hook.py:479} INFO - at org.apache.spark.storage.StorageUtils$.<clinit>(StorageUtils.scala)
[2022-03-30 20:59:14,158] {spark_submit_hook.py:479} INFO - at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:109)
[2022-03-30 20:59:14,159] {spark_submit_hook.py:479} INFO - at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:371)
[2022-03-30 20:59:14,160] {spark_submit_hook.py:479} INFO - at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:311)
[2022-03-30 20:59:14,160] {spark_submit_hook.py:479} INFO - at org.apache.spark.SparkEnv$.create(SparkEnv.scala:359)
[2022-03-30 20:59:14,161] {spark_submit_hook.py:479} INFO - at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:189)
[2022-03-30 20:59:14,162] {spark_submit_hook.py:479} INFO - at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
[2022-03-30 20:59:14,163] {spark_submit_hook.py:479} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:458)
[2022-03-30 20:59:14,164] {spark_submit_hook.py:479} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2022-03-30 20:59:14,165] {spark_submit_hook.py:479} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2022-03-30 20:59:14,166] {spark_submit_hook.py:479} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[2022-03-30 20:59:14,166] {spark_submit_hook.py:479} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-03-30 20:59:14,167] {spark_submit_hook.py:479} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2022-03-30 20:59:14,167] {spark_submit_hook.py:479} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2022-03-30 20:59:14,168] {spark_submit_hook.py:479} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2022-03-30 20:59:14,168] {spark_submit_hook.py:479} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2022-03-30 20:59:14,169] {spark_submit_hook.py:479} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2022-03-30 20:59:14,170] {spark_submit_hook.py:479} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2022-03-30 20:59:14,171] {spark_submit_hook.py:479} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2022-03-30 20:59:14,171] {spark_submit_hook.py:479} INFO - at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2022-03-30 20:59:14,172] {spark_submit_hook.py:479} INFO - at java.base/java.lang.Thread.run(Thread.java:831)
[2022-03-30 20:59:14,172] {spark_submit_hook.py:479} INFO - 
[2022-03-30 20:59:14,247] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:14 INFO ShutdownHookManager: Shutdown hook called
[2022-03-30 20:59:14,249] {spark_submit_hook.py:479} INFO - 22/03/30 20:59:14 INFO ShutdownHookManager: Deleting directory /private/var/folders/wt/20pgcb1j11323p97x03bt_g00000gr/T/spark-6c9c960d-cb10-4a45-905e-326aa50a8a47
[2022-03-30 20:59:14,706] {taskinstance.py:1150} ERROR - Cannot execute: /Users/rafa/Documents/python/spark/bin/spark-submit --master local --name twitter_transformation /Users/rafa/Documents/python/datapipeline/spark/transformation.py --src /Users/rafa/Documents/python/datapipeline/datalake/bronze/twitter_aluraonline/extract_date=2022-03-26 --dest /Users/rafa/Documents/python/datapipeline/datalake/silver/twitter_aluraonline/ --process-date 2022-03-26. Error code is: 1.
Traceback (most recent call last):
  File "/Users/rafa/Documents/python/datapipeline/.env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/rafa/Documents/python/datapipeline/.env/lib/python3.8/site-packages/airflow/contrib/operators/spark_submit_operator.py", line 187, in execute
    self._hook.submit(self._application)
  File "/Users/rafa/Documents/python/datapipeline/.env/lib/python3.8/site-packages/airflow/contrib/hooks/spark_submit_hook.py", line 403, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: /Users/rafa/Documents/python/spark/bin/spark-submit --master local --name twitter_transformation /Users/rafa/Documents/python/datapipeline/spark/transformation.py --src /Users/rafa/Documents/python/datapipeline/datalake/bronze/twitter_aluraonline/extract_date=2022-03-26 --dest /Users/rafa/Documents/python/datapipeline/datalake/silver/twitter_aluraonline/ --process-date 2022-03-26. Error code is: 1.
[2022-03-30 20:59:14,711] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=twitter_dag, task_id=transform_twitter_aluraonline, execution_date=20220326T090000, start_date=20220330T235859, end_date=20220330T235914
[2022-03-30 20:59:19,339] {local_task_job.py:102} INFO - Task exited with return code 1
